#!/usr/bin/env bash
# Debugging nginx to listen to port 80 and reloads the nginx master process
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
pgrep nginx -o > /run/nginx.pid
nginx -s reload
echo '' > /run/nginx.pid
